services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/host/wslg/runtime-dir
      - PULSE_SERVER=/mnt/host/wslg/PulseServer
      - QT_X11_NO_MITSHM=1
    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/host/wslg
    network_mode: host # for using localhost without port mapping
    devices:
      - /dev/dri:/dev/dri # for GPU acceleration
      # - /dev/bus/usb:/dev/bus/usb # for USB devices
      # - /dev/input:/dev/input # for input devices
      # - /dev/snd:/dev/snd # for sound devices
      # - /dev/video0:/dev/video0 # for video devices
    command: bash -c "roscore"
